### ISSUE TITLE
frontend authentication

### ISSUE THREAD

**Issue by mcorbin** [mcorbin/meuse#15]
Currently, there is no authentication.
We should decide which authentication mechanism we want to use.

**Comment by paulvt** [comment]
Hi! I came here to file a ticket to disable frontend authentication and then I saw this one and it got me confused, because it says there is no authentication?

In the setup at our company, we'd like to interface with Meuse, similar as with crates.io. I.e. you can browse the frontend and query the API anonymously (the instance is only available on the internet) and you need tokens to publish or do other administrative API calls that require non-read-only privileges.

Is it possible to have some flag that will allow for a fallback to "read-only" role permissions in case of no authorization is provided?

I could create a user "read-only" with role "read-only" but it is not as nice for my colleagues if they just want to look up some crate version.

**Comment by mcorbin** [comment]
Hello,

Thanks for your interest for the project.

I indeed released frontend authentication in the latest release, but forgot to close this issue.

> Is it possible to have some flag that will allow for a fallback to "read-only" role permissions in case of no authorization is provided?

It should be easy to implement, I will take a look at this soon.

**Comment by mcorbin** [comment]
@paulvt I've done a new release of the project. 

You can now disable the frontend authentication with `public: true` in the `frontend` section of the configuration (doc: https://meuse.mcorbin.fr/installation/configuration/).

**Comment by paulvt** [comment]
I tested and deploy it, thanks for the quick implementation.

(Btw, note that the 0.4.1 release didn't contain the JAR file.)

**Comment by mcorbin** [comment]
> (Btw, note that the 0.4.1 release didn't contain the JAR file.)

Thanks, I added the jar in the release.
