### ISSUE TITLE
Missing CSS after deployment

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [mcorbin/meuse#24]
Hello,

I have configured my Meuse, that's awesome project, the first one usable for Rust private registry in private.

I just received that error:
```
front:2 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://crates.media-io.com/static/css/style.css".
front:2 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://crates.media-io.com/static/css/bootstrap.min.css".
```

Which render me the page without any css. Pretty bad design :P
Do you think it's possible to set the MIME type to "text/css" ?

I don't know Closure to contribute...

Best regards,
Marc-Antoine

**Comment by mcorbin** [comment]
Hello,

You are right, I was not setting the content-type for static resources (but I missed it because it seems my browser does not care :p).

This commit (https://github.com/mcorbin/meuse/commit/47dd69bb8ed62c30ce9f70f8603f164512b4b7bb) solves the issue. The content-type header is now set to text/avascript for javascript files, text/css for css files...
I plan to do a release next week (I have a couple of improvements/refactorings which are ready to land). In the meantime you can build the jar by following this doc (https://meuse.mcorbin.fr/installation/get-meuse/) if you want to.

> I have configured my Meuse, that's awesome project, the first one usable for Rust private registry in private.

Thanks you ;) Don't hesitate to give me feedbacks or ideas for new features you would like to see.

**Comment by MarcAntoine-Arnaud** [comment]
Thank you for this very quick update !
I have merge on my fork and it works perfectly.

I create some issues to present some new features.
